### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by vweevers** [vweevers/remark-git-contributors#21]
@wooorm I wanted to release 1.0.0 but have some questions about the process. I came across the governance draft (https://github.com/unifiedjs/governance/pull/2) and until that's finalized I am wondering what the rules are for `remark-git-contributors` specifically.

1. Who may release: you (as lead), the remark team and/or me (as original author)?
1. Is there a standardized changelog format? I like [`Keep a Changelog`](https://keepachangelog.com/en/1.0.0/) ([example](https://github.com/Level/leveldown/blob/master/CHANGELOG.md), [example with commit/issue refs](https://github.com/Level/level-js/blob/master/CHANGELOG.md)) but will gladly adapt to the org's common format for consistency.
1. Is there a `remark` preset we can run on `remark-git-contributors` itself?
1. In addition to a changelog in GitHub releases, do we want a `CHANGELOG.md`? I like it for two reasons. First, offline availability. Second, changelogs would be PR-ed like any other change. This is especially important when following `Keep a Changelog` because its goal is to write a changelog by humans for humans. That means clarifying commit messages, summarizing related commits, excluding obsolete commits. Once that is approved and merged, it can be copied verbatim to the GH release. In my experience, this workflow produces better changelogs (reducing support requests) and makes releasing a shared responsibility (reducing stress). Within a team it does take a few iterations to get to a fast, bikeshed-free flow.

That's too many questions for a small project like `remark-git-contributors`; I'm also asking as a maintainer of other projects. To learn from each other :)

**Comment by wooorm** [comment]
Hey sorry, was busy writing up the tooling on how to manage team members (across organizations), currently in [remarkjs/governance](https://github.com/remarkjs/governance/blob/master/script/github-sync.js) but we’re planning on moving automation stuff over to some `unifiedjs/tooling` monorepo. Maybe of interest for your Level work?

I think unifiedjs/governance#2 is almost there, to be merged, but it’ll be a draft for a bit (to signal that we’re still actively looking for feedback).

For your questions:

> 1. Who may release: you (as lead), the remark team and/or me (as original author)?

The `@remarkjs/releasers` team, that’s currently me and `@johno`.

As an [outside collaborator](https://github.com/remarkjs/governance/blob/cbaef89e1c5863261c8354a5fcb8f7a6d75b9990/collaborators.json#L14-L19), you have write rights on this repository. That means you can merge PRs. Additionally, you have the same right/responsibility as other `@remarkjs/members` **in this repo** to vote on proposals in the consensus seeking phase (we’re still working on describing that).

All of this is still being drafted btw, so we’d appreciate feedback, and if you’re up for it we can also discuss adding you to the team.

> 3. Is there a remark preset we can run on remark-git-contributors itself?

Yep! We’ve got some standard process for all the readmes under @unifiedjs already. Can I create a PR for that?

> 2. Is there a standardized changelog format? I like Keep a Changelog (example, example with commit/issue refs) but will gladly adapt to the org's common format for consistency.
> 
> 4. In addition to a changelog in GitHub releases, do we want a CHANGELOG.md? I like it for two reasons. First, offline availability. Second, changelogs would be PR-ed like any other change. This is especially important when following Keep a Changelog because its goal is to write a changelog by humans for humans. That means clarifying commit messages, summarizing related commits, excluding obsolete commits. Once that is approved and merged, it can be copied verbatim to the GH release. In my experience, this workflow produces better changelogs (reducing support requests) and makes releasing a shared responsibility (reducing stress). Within a team it does take a few iterations to get to a fast, bikeshed-free flow.

There is no such format, but I do run `git log --pretty=oneline --graph --abbrev-commit` (as an alias) and add the results, cleaned, to releases.

I used to keep changelogs, but stepped away because a) I don’t really care about offline availability, b) I find it weird maintaining a git log in the git tree. The need for a changelog, compared to the git log, evaporates a bit because I squash PRs, and I typically document significant commits thoroughly already. I can almost always just copy the git log to releases verbatim, dropping a few useless commits.

Even though I see a bunch of support requests, I don’t think I never see requests I believe after a new version!

> makes releasing a shared responsibility (reducing stress).

How?

> Within a team it does take a few iterations to get to a fast, bikeshed-free flow.

Could you expand on workflows that work (e.g., level)?

**Comment by vweevers** [comment]
Many thanks for the elaborate answer. First things first: could you release 1.0.0 soon?

> if you’re up for it we can also discuss adding you to the team.

Not at this time, unless I'm mistaken about what it entails. I'd describe my current use of `remarkjs` as non-essential tooling. I don't have enough incentive or time to make a commitment to the org. I'll gladly make a commitment to this subproject though, if there's a way to give me release rights that won't also suck me into other projects (by expectations that people may have, or practically speaking, by `@mentions`).

> We’ve got some standard process for all the readmes under @unifiedjs already. Can I create a PR for that?

👍

**Comment by vweevers** [comment]
**Re: changelogs:** I can see how in your workflow, changelogs are redundant. It wouldn't work in Level, which apart from the very loose [OPEN Open Source](http://openopensource.org/) has no governance policy. We sometimes merge fast. PRs (esp. from new contributors) don't have to be perfect. That leads to follow-up commits that are not relevant for the changelog. We don't always squash, keeping commits for bisecting or authorship. Many commit messages can be clarified later on, even our own, because one tends to describe a commit in the moment, out of touch with larger goals.

Given all that, the changelog is essential. The git log describes what we did _step by step_, the changelog summarizes what the _end result_ means for consumers. And following Keep a Changelog, we categorize the changes under `Changed`, `Added`, `Fixed` and `Removed` headers. That helps both consumers and maintainers ("When did we fix bug X?").

> > makes releasing a shared responsibility (reducing stress).
>
> How?

I personally hate releasing and the ever-present risk of ecosystem breakage, so if any part of a release process can be peer-reviewed, I welcome it. Reviewing the changelog together serves as a final check: are we all good with releasing this set of changes as a semver-minor (for example)? In addition, it keeps maintainers in the loop, even if they didn't participate in (all) code PRs.

> Could you expand on workflows that work (e.g., level)?

It's mostly about filling gaps in the Keep a Changelog "specification", regarding wording, consistent descriptions of common maintenance tasks, sorting of changelog items, linking to background info (issues, PRs, commits). With a clear set of rules (as well as some remark tooling, wink) changelog PRs are fast. We haven't written those rules down yet.

**Comment by wooorm** [comment]
> Not at this time, unless I'm mistaken about what it entails.

Makes sense! 👍

> [...] Reviewing the changelog together serves as a final check [...] it keeps maintainers in the loop, even if they didn't participate in (all) code PRs.

I like this part, this makes sense. GH releases doesn’t offer that. I guess an issue could suffice tho?

> With a clear set of rules (as well as some remark tooling, wink) changelog PRs are fast. We haven't written those rules down yet.

Interested in seeing those if they’re ever written down!

---

As we’re about to cut 1.0.0, I think this changelog gets useful from now on.
How about we meet in the middle and use GH releases, but use the sections suggested by Keep a Changelog?

**Comment by vweevers** [comment]
> I like this part, this makes sense. GH releases doesn’t offer that. I guess an issue could suffice tho?

I suppose it depends on the type of feedback that you want. If you only want people to sign off on the set of changes - rather than how those changes are described - an issue suffices, yea.

> As we’re about to cut 1.0.0, I think this changelog gets useful from now on.
How about we meet in the middle and use GH releases, but use the sections suggested by Keep a Changelog?

Alright! 

I think all questions here have been answered, so I suggest to close.
